INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('mineral water 1l','bottle',1,2);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('mineral water 0.5l','bottle',0,1);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('apple juice','bottle',1,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('orange juice','bottle',0,1);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('Sprite 0.5l','bottle',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('Coca-cola 0.5l','bottle',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('Pepsi 0.5l','bottle',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('baguette',1,2);
INSERT INTO groceries (NAME,owned,needed) VALUES ('white bread',1,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('wholemeal bread',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('burger bun',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('multi-seed roll',0,3);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('white basmati rice','dkg',10,20);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('brown rice','dkg',0,100);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('flour 450','kg',1,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('white sugar','kg',0,1);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('brown sugar','kg',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('cheddar cheese','dkg',0,25);
INSERT INTO groceries (NAME,owned,needed) VALUES ('camembert',2,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('butter',1,1);
INSERT INTO groceries (NAME,owned,needed) VALUES ('cottage cheese',1,2);
INSERT INTO groceries (NAME,owned,needed) VALUES ('mozzarella',1,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('milk 3.2%','bottle',1,1);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('milk 2.0%','bottle',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('mascarpone','dkg',0,40);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('gouda cheese','dkg',15,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('natural yoghurt','ml',200,400);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('strawberry yoghurt','ml',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('greek yoghurt','ml',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('apple','dkg',100,200);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('cucumber','dkg',30,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('bell pepper','dkg',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('pear','dkg',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('mushroom','dkg',100,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('ginger','dkg',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('onion','dkg',80,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('carrot','dkg',50,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('celery','dkg',0,75);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('beetroot','dkg',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('potato','dkg',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('Snickers',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('Kinder Chocolate',1,2);
INSERT INTO groceries (NAME,owned,needed) VALUES ('Milka Oreo',1,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('Wedel dark chocolate',0,0);
INSERT INTO groceries (NAME,owned,needed) VALUES ('Prince polo',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('honey','jar',0,1);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('strawberry jam','jar',1,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('black olives','jar',0,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('green olives','jar',1,0);
INSERT INTO groceries (NAME,unit,owned,needed) VALUES ('dried tomatoes','jar',1,1);