INSERT INTO party (type, participants) VALUES ('coffee', 'Marek, Ania');
INSERT INTO party (type, participants) VALUES ('coffee', 'Ania');
INSERT INTO party (type, participants) VALUES ('coffee', 'Robert');
INSERT INTO party (type, participants) VALUES ('coffee', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('lunch', 'Marek, Ania');
INSERT INTO party (type, participants) VALUES ('lunch', 'Ania');
INSERT INTO party (type, participants) VALUES ('lunch', 'Robert');
INSERT INTO party (type, participants) VALUES ('lunch', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('lunch', 'Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('lunch', 'Marek, Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('lunch', 'Zosia');
INSERT INTO party (type, participants) VALUES ('club', 'Robert');
INSERT INTO party (type, participants) VALUES ('club', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('club', 'Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('club', 'Marek, Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('club', 'Zosia, Marek');
INSERT INTO party (type, participants) VALUES ('club', 'Marek');
INSERT INTO party (type, participants) VALUES ('bowling', 'Marek, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('bowling', 'Ania, Robert, Piotr');
INSERT INTO party (type, participants) VALUES ('bowling', 'Robert, Piotr, Marcin');
INSERT INTO party (type, participants) VALUES ('bowling', 'Robert, Ania, Piotr, Marcin, Kuba');
INSERT INTO party (type, participants) VALUES ('mulled wine', 'Marek, Ania');
INSERT INTO party (type, participants) VALUES ('mulled wine', 'Ania, Zosia, Piotr');
INSERT INTO party (type, participants) VALUES ('mulled wine', 'Robert, Paulina');
INSERT INTO party (type, participants) VALUES ('mulled wine', 'Robert, Marek, Kasia');
INSERT INTO party (type, participants) VALUES ('exhibition', 'Marek, Ania, Robert, Jacek');
INSERT INTO party (type, participants) VALUES ('exhibition', 'Ania, Piotr');
INSERT INTO party (type, participants) VALUES ('exhibition', 'Robert');
INSERT INTO party (type, participants) VALUES ('exhibition', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('dinner', 'Marek, Ania, Kasia');
INSERT INTO party (type, participants) VALUES ('dinner', 'Ania, Kuba');
INSERT INTO party (type, participants) VALUES ('dinner', 'Robert');
INSERT INTO party (type, participants) VALUES ('dinner', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('dinner', 'Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('dinner', 'Marek, Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('dinner', 'Zosia, Robert');
INSERT INTO party (type, participants) VALUES ('beer', 'Robert');
INSERT INTO party (type, participants) VALUES ('beer', 'Robert, Ania');
INSERT INTO party (type, participants) VALUES ('beer', 'Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('beer', 'Marek, Robert, Ania, Zosia');
INSERT INTO party (type, participants) VALUES ('beer', 'Zosia, Marek');
INSERT INTO party (type, participants) VALUES ('beer', 'Marek');
INSERT INTO party (type, participants) VALUES ('match', 'Marek, Ania, Zosia, Robert');
INSERT INTO party (type, participants) VALUES ('match', 'Ania, Robert, Piotr');
INSERT INTO party (type, participants) VALUES ('match', 'Robert, Piotr, Marcin');
INSERT INTO party (type, participants) VALUES ('match', 'Robert, Ania, Piotr, Marcin, Kuba');
INSERT INTO party (type, participants) VALUES ('cinema', 'Marek, Ania, Kuba');
INSERT INTO party (type, participants) VALUES ('cinema', 'Ania, Zosia, Piotr');
INSERT INTO party (type, participants) VALUES ('cinema', 'Robert, Paulina, Kuba');
INSERT INTO party (type, participants) VALUES ('cinema', 'Robert, Marek, Kasia');