INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Pilsudskiego 105, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Swidnicka 40, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Sucha 1, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Szewska 6/7, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Komandorska 147, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Biedronka', 'ul. Duboisa 9, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Lidl', 'ul. Braniborska 82, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Lidl', 'ul. Borowska 134, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Lidl', 'ul. Muchoborska 17, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('IKEA', 'ul. Czekoladowa 5, Bielany Wroclawskie');
INSERT INTO places (NAME,address) VALUES ('Super-pharm', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Douglas', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('DOZ Apteka', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('hebe', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('ROSSMANN', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Yves Rocher', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('martes', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('4f', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('home&you', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('DUKA', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Ochnik', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('wojas', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Czas na Herbate', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Delikatesy T&J', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('empik', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Media Markt', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Carto Store', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Super-pharm', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Big Star', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('H&M', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Lavard', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('LEVIS', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Medicine', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('RESERVED', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('ZARA', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Super-pharm', 'plac Grunwaldzki 22, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Kaufland', 'ul. Sieradzka 7, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Kaufland', 'ul. Jana Dlugosza 74, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Kaufland', 'ul. Bardzka 1A, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Kaufland', 'ul. Legnicka 62, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Auchan', 'ul. Zwycieska 14b, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Auchan', 'ul. Hubska 102-118, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Auchan', 'ul. Krzywoustego 126, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('hebe', 'ul. Olawska 13, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('hebe', 'ul. Sucha 1, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('hebe', 'ul. Nowy Targ 28, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Zabka', 'ul. Komandorska 8-12, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Zabka', 'ul. Pilsudskiego 105, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Zabka', 'ul. Podwale 66/2b, Wroclaw');
INSERT INTO places (NAME,address) VALUES ('Zabka', 'ul. Ruska 61/1, Wroclaw');