INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Dove soap original','bar',1,1);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Nivea shower gel','bottle',0,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('black t-shirt',4,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('white t-shirt',1,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('white teacup',3,3);
INSERT INTO stuff (NAME,owned,needed) VALUES ('physics textbook',24,17);
INSERT INTO stuff (NAME,owned,needed) VALUES ('notebook A4',2,3);
INSERT INTO stuff (NAME,owned,needed) VALUES ('notebook A5',5,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('black pen',3,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('blue pen',2,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('pencil',0,2);
INSERT INTO stuff (NAME,owned,needed) VALUES ('ruler',1,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('backpack',2,0);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('tissues','box',0,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('red jumper',0,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Hauga wardrobe',0,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('LERHAMN Table',0,1);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Elmex toothpaste','tube',1,1);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('garbage bag','30 bag/roll',0,2);
INSERT INTO stuff (NAME,owned,needed) VALUES ('hairbrush',1,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('hairpin',3,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Perwoll washing detergent for white',0,1);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Perwoll washing detergent for black',1,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Perwoll washing detergent for colors',1,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Lenor fabric softener blue',1,0);
INSERT INTO stuff (NAME,owned,needed) VALUES ('Lenor fabric softener green',1,0);
INSERT INTO stuff (NAME,unit,owned) VALUES ('aluminum foil','roll',1);
INSERT INTO stuff (NAME,unit,owned) VALUES ('baking paper','roll',1);
INSERT INTO stuff (NAME,owned) VALUES ('jar 470 ml',2);
INSERT INTO stuff (NAME,owned) VALUES ('jar 220 ml',1);
INSERT INTO stuff (NAME,owned) VALUES ('jar 740 ml',3);
INSERT INTO stuff (NAME,owned) VALUES ('glass 150 ml',2);
INSERT INTO stuff (NAME,owned) VALUES ('glass 250 ml',1);
INSERT INTO stuff (NAME,owned) VALUES ('glass 300 ml',3);
INSERT INTO stuff (NAME,unit,owned) VALUES ('white paint','100 ml tube',1);
INSERT INTO stuff (NAME,unit,owned) VALUES ('black paint','100 ml tube',1);
INSERT INTO stuff (NAME,unit,owned) VALUES ('yellow paint','100 ml tube',1);
INSERT INTO stuff (NAME,unit,owned) VALUES ('green paint','100 ml tube',1);
INSERT INTO stuff (NAME,unit,needed) VALUES ('blue paint','100 ml tube',1);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Finish Quantum Ultimate Lemon','tablet',21, 68);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Fairy All In One Dishwasher Original','tablet',11, 0);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('Fairy All In One Dishwasher Lemon','tablet',11, 0);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('kitchen towel','roll',1, 1);
INSERT INTO stuff (NAME,unit,owned,needed) VALUES ('shampoo for cats','bottle',0, 12);
INSERT INTO stuff (NAME,needed) VALUES ('Mahlkoenig coffee grinder',2);
INSERT INTO stuff (NAME) VALUES ('hdmi cable');
INSERT INTO stuff (NAME,unit) VALUES ('Fairy Washing Up Liquid Original','bottle');
INSERT INTO stuff (NAME,needed) VALUES ('Lightbulb LED 40W',2);
INSERT INTO stuff (NAME,needed) VALUES ('Lightbulb LED 100W',1);
INSERT INTO stuff (NAME,needed) VALUES ('Vileda mop refill',1);